"use client"

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'zh';
  setLanguage: (lang: 'en' | 'zh') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译数据
const translations = {
  en: {
    'nav.home': 'Home',
    'nav.aiGenerator': 'AI Generator',
    'nav.gallery': 'Gallery',
    'nav.about': 'About Us',
    'nav.getStarted': 'Get Started',
    'hero.title': 'Transform Your Ideas Into Stunning Art',
    'hero.subtitle': 'Create beautiful, unique artwork in seconds with our advanced AI image generation technology',
    'hero.cta': 'Start Creating Now',
    'hero.learnMore': 'Learn More',
    
         // What Section
     'what.title': 'What is Nano Banana?',
     'what.subtitle': 'An AI-powered platform that transforms your text descriptions into stunning visual artwork',
     'what.feature1.title': 'AI-Powered Generation',
     'what.feature1.desc': 'Advanced artificial intelligence transforms your text descriptions into stunning, unique artwork in seconds',
     'what.feature2.title': 'Multiple Art Styles',
     'what.feature2.desc': 'Choose from photorealistic, cartoon, oil painting, watercolor, and dozens of other artistic styles',
     'what.feature3.title': 'High-Quality Output',
     'what.feature3.desc': 'Generate images in high resolution up to 4K quality, perfect for printing and professional use',
     'what.feature4.title': 'Lightning Fast',
     'what.feature4.desc': 'Get your custom artwork in under 30 seconds. No waiting, no delays - just instant creativity',
    
         // Why Section
     'why.title': 'Why Choose Nano Banana?',
     'why.subtitle': 'Experience the future of digital art creation',
     'why.reason1.title': 'Privacy & Security',
     'why.reason1.desc': 'Your prompts and generated images are completely private. We never store or share your creative content without permission',
     'why.reason1.stats': '100% Private',
     'why.reason2.title': 'Trusted by Creators',
     'why.reason2.desc': 'Join over 500,000 artists, designers, and creators who rely on Nano Banana for their creative projects',
     'why.reason2.stats': '500K+ Users',
     'why.reason3.title': 'Industry Leading',
     'why.reason3.desc': 'Our AI models are trained on the latest technology, delivering superior quality compared to other platforms',
     'why.reason3.stats': '4.9/5 Rating',
     'why.reason4.title': 'Constantly Improving',
     'why.reason4.desc': 'We regularly update our AI models and add new features based on user feedback and technological advances',
     'why.reason4.stats': 'Weekly Updates',
     'why.stats.uptime': 'Uptime Guarantee',
     'why.stats.support': 'Customer Support',
     'why.stats.images': 'Images Generated',
     'why.stats.styles': 'Art Styles',
    
         // How Section
     'how.title': 'How It Works',
     'how.subtitle': 'Three simple steps to create your masterpiece',
     'how.step1.title': 'Enter your prompt',
     'how.step1.desc': 'Describe your vision in simple words. Be as creative and detailed as you want',
     'how.step2.title': 'Choose your style',
     'how.step2.desc': 'Select from various artistic styles like photorealistic, cartoon, oil painting, and more',
     'how.step3.title': 'Download your art',
     'how.step3.desc': 'Get your stunning AI-generated artwork in high resolution, ready to use anywhere',
    
    // Stats Section
    'stats.images': 'Images Created',
    'stats.users': 'Active Users',
    'stats.uptime': 'Uptime',
    'stats.support': 'Support',
    
         // Testimonials
     'testimonials.title': 'What Our Users Say',
     'testimonials.subtitle': 'Join thousands of satisfied creators who have transformed their ideas into stunning artwork with Nano Banana. Here\'s what they have to say about their Nano Banana experience',
     'testimonials.user1.name': 'Sarah Chen',
     'testimonials.user1.role': 'Digital Artist',
     'testimonials.user1.text': 'Nano Banana has revolutionized my creative workflow. The quality of AI-generated images is absolutely stunning, and the variety of styles available is incredible. I use it daily for my client projects.',
     'testimonials.user2.name': 'Marcus Rodriguez',
     'testimonials.user2.role': 'Marketing Director',
     'testimonials.user2.text': 'As a marketing professional, I need high-quality visuals quickly. Nano Banana delivers exactly that. The speed and quality are unmatched, and it has saved our team countless hours and budget.',
     'testimonials.user3.name': 'Emily Watson',
     'testimonials.user3.role': 'Content Creator',
     'testimonials.user3.text': 'I was skeptical about AI art at first, but Nano Banana completely changed my mind. The images are so detailed and creative - sometimes even better than what I had imagined. It\'s like having a personal artist.',
     'testimonials.user4.name': 'David Kim',
     'testimonials.user4.role': 'Game Developer',
     'testimonials.user4.text': 'For concept art and game assets, Nano Banana is a game-changer. The variety of styles and the ability to iterate quickly has accelerated our development process significantly. Highly recommended!',
     'testimonials.user5.name': 'Lisa Thompson',
     'testimonials.user5.role': 'Small Business Owner',
     'testimonials.user5.text': 'Running a small business, I needed affordable yet professional visuals for my marketing. Nano Banana provides exactly that. The quality rivals expensive stock photos, but with complete customization.',
     'testimonials.user6.name': 'Alex Johnson',
     'testimonials.user6.role': 'Freelance Designer',
     'testimonials.user6.text': 'The creative possibilities with Nano Banana are endless. I can explore ideas and concepts that would take hours to create manually. It\'s become an essential tool in my design arsenal.',
    
         // FAQ Section
     'faq.title': 'Frequently Asked Questions',
     'faq.subtitle': 'Everything you need to know about Nano Banana',
     'faq.contact': 'Still have questions? We\'re here to help!',
     'faq.contactButton': 'Contact Support',
     'faq.q1': 'How does Nano Banana work?',
     'faq.a1': 'Nano Banana uses advanced AI models to interpret your text descriptions and generate corresponding images. Simply type what you want to see, select your preferred style, and our AI will create a unique artwork in seconds.',
     'faq.q2': 'What kind of images can I generate?',
     'faq.a2': 'You can generate virtually any type of image - from realistic photographs to abstract art, cartoons, landscapes, portraits, fantasy scenes, and more. Our AI supports over 150 different artistic styles and can handle complex, detailed prompts.',
     'faq.q3': 'Is there a limit to how many images I can create?',
     'faq.a3': 'Free users can generate up to 10 images per day. Premium subscribers get unlimited generations, priority processing, and access to advanced features like higher resolutions and exclusive art styles.',
     'faq.q4': 'What resolution are the generated images?',
     'faq.a4': 'Free users receive images at 1024x1024 pixels. Premium users can generate images up to 4K resolution (4096x4096 pixels), perfect for printing and professional use.',
     'faq.q5': 'Can I use the generated images commercially?',
     'faq.a5': 'Yes! All images generated with Nano Banana can be used for commercial purposes. You retain full rights to your creations, including the ability to sell, modify, and distribute them as you wish.',
     'faq.q6': 'How long does it take to generate an image?',
     'faq.a6': 'Most images are generated within 15-30 seconds. Premium users enjoy priority processing, which can reduce generation time to as little as 10 seconds during peak hours.',
     'faq.q7': 'What makes Nano Banana different from other AI generators?',
     'faq.a7': 'Nano Banana focuses on quality, speed, and user experience. We use the latest AI models, offer more artistic styles than competitors, provide better prompt understanding, and maintain the highest image quality standards in the industry.',
     'faq.q8': 'Is my data safe and private?',
     'faq.a8': 'Absolutely. We take privacy seriously. Your prompts and generated images are encrypted and never shared with third parties. You can delete your account and all associated data at any time.',
    
         // Footer
     'footer.company': 'Company',
     'footer.product': 'Product',
     'footer.support': 'Support',
     'footer.legal': 'Legal',
     'footer.copyright': '© 2025 Nano Banana. All rights reserved.',
     'footer.madeWith': 'Made with ❤️ for creators',
     'footer.poweredBy': 'Powered by AI',
     'footer.about': 'About Us',
     'footer.careers': 'Careers',
     'footer.press': 'Press',
     'footer.blog': 'Blog',
     'footer.features': 'Features',
     'footer.pricing': 'Pricing',
     'footer.api': 'API',
     'footer.help': 'Help Center',
     'footer.community': 'Community',
     'footer.contact': 'Contact Us',
     'footer.terms': 'Terms of Service',
     'footer.privacy': 'Privacy Policy',
     'footer.cookies': 'Cookie Policy',
     'footer.gdpr': 'GDPR',
     'footer.description': 'Transform your imagination into stunning artwork with Nano Banana\'s cutting-edge AI technology. Create, share, and discover amazing images from simple text prompts with Nano Banana.',
    
         // Call to Action
     'cta.title': 'Ready to Create Your Masterpiece?',
     'cta.subtitle': 'Join thousands of artists and creators who are already using Nano Banana',
     'cta.button': 'Get Started Now',
     'cta.badge': 'Start Creating Today',
     'cta.pricing': 'View Pricing',
     'cta.stats.images': 'Images Created',
     'cta.stats.users': 'Active Users',
     'cta.stats.uptime': 'Uptime',
     'cta.stats.support': 'Support',
     'testimonials.stats.averageRating': 'Average Rating',
     'testimonials.stats.happyUsers': 'Happy Users',
     'testimonials.stats.imagesGenerated': 'Images Generated',
     'testimonials.stats.satisfactionRate': 'Satisfaction Rate',
    
         // Gallery
     'gallery.title': 'Gallery of Creations',
     'gallery.subtitle': 'Explore stunning artworks created by our community using Nano Banana\'s AI technology. Get inspired and create your own masterpieces with Nano Banana',
     'gallery.loadMore': 'Load More Works',
     'gallery.prompt': 'Prompt:',
     'gallery.image1.title': 'Mystical Forest',
     'gallery.image1.desc': 'A magical forest with glowing mushrooms and ethereal light',
     'gallery.image2.title': 'Futuristic Cityscape',
     'gallery.image2.desc': 'A cyberpunk city with neon lights and flying cars',
     'gallery.image3.title': 'Ocean Sunset',
     'gallery.image3.desc': 'A serene ocean scene with vibrant sunset colors',
     'gallery.image4.title': 'Mountain Landscape',
     'gallery.image4.desc': 'Majestic mountains with dramatic clouds and lighting',
     'gallery.image5.title': 'Space Galaxy',
     'gallery.image5.desc': 'A stunning view of distant galaxies and nebulae',
     'gallery.image6.title': 'Abstract Art',
     'gallery.image6.desc': 'Vibrant abstract composition with flowing colors',
     'gallery.image7.title': 'Wildlife Portrait',
     'gallery.image7.desc': 'A detailed portrait of a majestic wildlife creature',
     'gallery.image8.title': 'Architectural Wonder',
     'gallery.image8.desc': 'Modern architecture with unique geometric patterns',
     'gallery.image9.title': 'Vintage Car',
     'gallery.image9.desc': 'Classic vintage car in a nostalgic setting',
     'gallery.prompt1': 'magical forest with glowing mushrooms, ethereal lighting, fantasy art',
     'gallery.prompt2': 'cyberpunk city, neon lights, flying cars, futuristic architecture',
     'gallery.prompt3': 'ocean sunset, vibrant colors, peaceful waves, golden hour',
     'gallery.prompt4': 'majestic mountains, dramatic clouds, epic landscape photography',
     'gallery.prompt5': 'distant galaxies, colorful nebulae, space photography, stars',
     'gallery.prompt6': 'abstract art, vibrant colors, flowing patterns, digital painting',
     'gallery.prompt7': 'wildlife portrait, detailed fur, natural habitat, professional photography',
     'gallery.prompt8': 'modern architecture, geometric patterns, glass and steel, urban design',
     'gallery.prompt9': 'vintage car, classic design, nostalgic atmosphere, retro photography',
     'draw.prompt': 'Generated from prompt:',
     'hero.examplePrompt': 'Scene of several ducks swimming in the water',
     'draw.title': 'AI Image Generator',
     'draw.subtitle': 'Transform your ideas into stunning artwork with our advanced AI technology',
     'draw.promptPlaceholder': 'Describe what you want to see...',
     'draw.styleLabel': 'Art Style',
     'draw.sizeLabel': 'Image Size',
     'draw.generateButton': 'Generate Image',
     'draw.generating': 'Generating...',
     'draw.downloadButton': 'Download',
     'draw.favoriteButton': 'Favorite',
     'draw.regenerateButton': 'Regenerate',
     'draw.successMessage': 'Image generated successfully!',
     'draw.errorMessage': 'Generation failed, please try again',
     'draw.waitingForGeneration': 'Waiting for generation',
     'draw.success': 'Success',
     'draw.describeYourIdea': 'Describe Your Idea',
     'draw.describeYourIdeaDesc': 'Describe in detail what kind of image you want to generate',
     'draw.result': 'Generation Result',
     'draw.enterPromptAndClick': 'Enter a prompt and click the generate button',
     'draw.styleRealistic': '🎭 Realistic Style - Photorealistic effect',
     'draw.styleAnime': '🎌 Anime Style - Japanese anime style',
     'draw.styleOilPainting': '🖼️ Oil Painting Style - Classical oil painting art',
     'draw.styleWatercolor': '💧 Watercolor Style - Soft watercolor painting',
     'draw.styleSketch': '✏️ Sketch Style - Black and white sketch art',
     'draw.sizeSquare': '⬜ Square',
     'draw.sizePortrait': '📱 Portrait',
     'draw.sizeLandscape': '🖥️ Landscape',
     'draw.sizeWidescreen': '🎬 Widescreen',
     'draw.sizeMobilePortrait': '📱 Mobile Portrait',
     'draw.tip': 'Tip: The more detailed your description, the more the generated image will match your imagination',
     'draw.generatedImage': 'Generated Image',
     'draw.generationFailed': 'Generation failed',
     'about.badge': 'About Nano Banana',
     'about.title': 'Revolutionizing AI Art Creation',
     'about.subtitle': 'Nano Banana is at the forefront of AI-powered creativity, empowering artists, designers, and creators to bring their wildest imaginations to life through cutting-edge artificial intelligence technology.',
     'about.mission.title': 'Our Mission',
     'about.mission.desc': 'To democratize art creation by making professional-grade AI image generation accessible to everyone. We believe that creativity should have no boundaries, and technology should amplify human imagination, not replace it.',
     'about.vision.title': 'Our Vision',
     'about.vision.desc': 'A world where anyone can create stunning artwork in seconds, where ideas flow freely from mind to canvas, and where AI serves as the ultimate creative companion for human expression and innovation.',
     'about.feature1.title': 'Advanced AI Technology',
     'about.feature1.desc': 'Powered by state-of-the-art machine learning models, delivering high-quality, creative, and unique artwork generation.',
     'about.feature2.title': 'User-Centric Design',
     'about.feature2.desc': 'Intuitive interface designed for creators of all skill levels, from beginners to professional artists and designers.',
     'about.feature3.title': 'Privacy & Security',
     'about.feature3.desc': 'Enterprise-grade security measures to protect your creative work and ensure your intellectual property remains safe.',
     'about.stats.images': 'Images Created',
     'about.stats.users': 'Active Users',
     'about.stats.uptime': 'Uptime',
     'about.stats.support': 'Support',
     'about.values.title': 'Our Values',
     'about.values.subtitle': 'These core principles guide everything we do at Nano Banana',
     'about.value1.title': 'Excellence',
     'about.value1.desc': 'We strive for excellence in every aspect of our service, from AI quality to user experience.',
     'about.value2.title': 'Creativity',
     'about.value2.desc': 'We celebrate and nurture creativity, believing it\'s the foundation of human progress.',
     'about.value3.title': 'Community',
     'about.value3.desc': 'We build and support a vibrant community of creators, artists, and innovators.',
     
     // Privacy Policy
     'privacy.badge': 'Privacy & Security',
     'privacy.title': 'Privacy Policy',
     'privacy.lastUpdated': 'Last Updated: January 2025',
     'privacy.section1.title': 'The Information We Collect',
     'privacy.section1.desc': 'We collect the information you directly provide to us, such as when you create an account, use our AI image generation service, or contact our support.',
     'privacy.section1.item1': 'Account Information (Email, Username)',
     'privacy.section1.item2': 'Usage Data and Generated Images',
     'privacy.section1.item3': 'Communication Preferences',
     'privacy.section1.item4': 'Technical information about your device and usage',
     'privacy.section2.title': 'How We Use Your Information',
     'privacy.section2.desc': 'We use the collected information to provide, maintain, and improve our services:',
     'privacy.section2.item1': 'Processing and generating AI images based on your prompts',
     'privacy.section2.item2': 'Providing customer support and responding to inquiries',
     'privacy.section2.item3': 'Improving our AI models and service quality',
     'privacy.section2.item4': 'Sending important updates and service notifications',
     'privacy.section2.item5': 'Ensuring security and preventing fraud',
     'privacy.section3.title': 'Data Security',
     'privacy.section3.desc': 'We implement appropriate security measures to protect your personal information:',
     'privacy.section3.item1': 'Encryption of data transmission and storage',
     'privacy.section3.item2': 'Regular security audits and updates',
     'privacy.section3.item3': 'Access control and authentication measures',
     'privacy.section3.item4': 'Secure data centers and infrastructure',
     'privacy.section4.title': 'Data Sharing',
     'privacy.section4.desc': 'We do not sell, trade, or rent your personal information to third parties. We may share information only in the following circumstances:',
     'privacy.section4.item1': 'With your explicit consent',
     'privacy.section4.item2': 'To comply with legal obligations',
     'privacy.section4.item3': 'To protect our rights and security',
     'privacy.section4.item4': 'With trusted service providers who assist us in operating our services',
     'privacy.section5.title': 'Your Rights',
     'privacy.section5.desc': 'You have the right to:',
     'privacy.section5.item1': 'Access and review your personal information',
     'privacy.section5.item2': 'Update or correct inaccurate information',
     'privacy.section5.item3': 'Request deletion of your data',
     'privacy.section5.item4': 'Opt out of marketing communications',
     'privacy.section5.item5': 'Export your data in portable format',
     'privacy.section6.title': 'Contact Us',
     'privacy.section6.desc': 'If you have any questions about this Privacy Policy or our data practices, please contact us:',
     'privacy.section6.email': 'Email: privacy@nanobananamodle.com',
     'privacy.section6.response': 'We will respond to your inquiry within 24 hours.',
     
     // Terms of Service
     'terms.badge': 'Legal & Terms',
     'terms.title': 'Terms of Service',
     'terms.lastUpdated': 'Last Updated: January 2025',
     'terms.section1.title': 'Acceptance of Terms',
     'terms.section1.desc': 'By accessing and using Nano Banana\'s AI image generation service, you agree to be bound by these terms of service. If you do not agree to these terms, please do not use our services.',
     'terms.section2.title': 'Service Description',
     'terms.section2.desc': 'Nano Banana provides an AI-driven image generation service that allows users to create artwork from text descriptions. Our services include:',
     'terms.section2.item1': 'Text-to-image generation using advanced AI models',
     'terms.section2.item2': 'Multiple artistic styles and customization options',
     'terms.section2.item3': 'High-quality image output in various formats',
     'terms.section2.item4': 'User-friendly interface and tools',
     'terms.section2.item5': 'Customer support and assistance',
     'terms.section3.title': 'User Responsibility',
     'terms.section3.desc': 'As a user of our services, you agree to:',
     'terms.section3.item1': 'Providing accurate and appropriate text prompts',
     'terms.section3.item2': 'Respecting intellectual property and copyright laws',
     'terms.section3.item3': 'Not using the service for illegal or harmful purposes',
     'terms.section3.item4': 'Not attempting to reverse engineer or hack our systems',
     'terms.section3.item5': 'Maintaining the security of your account credentials',
     'terms.section3.item6': 'Complying with all applicable laws and regulations',
     'terms.section4.title': 'Content Guidelines',
     'terms.section4.desc': 'You must not use our services to generate the following content:',
     'terms.section4.item1': 'Containing hate speech, violence, or discrimination',
     'terms.section4.item2': 'Infringing on intellectual property',
     'terms.section4.item3': 'Pornographic or inappropriate content',
     'terms.section4.item4': 'Promoting illegal activities or harmful behavior',
     'terms.section4.item5': 'Including personal information of others without consent',
     'terms.section4.item6': 'Intended to deceive or mislead',
     'terms.section5.title': 'Intellectual Property',
     'terms.section5.desc': 'Regarding the images you generate using our services:',
     'terms.section5.item1': 'You retain all rights to the generated images',
     'terms.section5.item2': 'You can use the images for personal and commercial purposes',
     'terms.section5.item3': 'We reserve the right to improve our services using the generated images',
     'terms.section5.item4': 'You are responsible for ensuring you have the right to use any referenced content',
     'terms.section6.title': 'Service Availability',
     'terms.section6.desc': 'We strive to maintain high service availability, but cannot guarantee:',
     'terms.section6.item1': '100% uptime or continuous availability',
     'terms.section6.item2': 'Instant response times during peak usage',
     'terms.section6.item3': 'Compatibility with all devices or browsers',
     'terms.section6.item4': 'Unlimited use',
     'terms.section7.title': 'Limitation of Liability',
     'terms.section7.desc': 'Nano Banana is not liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of our services.',
     'terms.section8.title': 'Terms of Service Changes',
     'terms.section8.desc': 'We reserve the right to modify these terms at any time. We will notify users of significant changes by email or through our services. Acceptance of the new terms constitutes acceptance of the new terms.',
     'terms.section9.title': 'Contact Information',
     'terms.section9.desc': 'If you have any questions about these terms of service, please contact us:',
     'terms.section9.email': 'Email: legal@nanobananamodle.com',
     'terms.section9.response': 'We will respond to your inquiry within 24 hours.',
  },
  zh: {
    'nav.home': '首页',
    'nav.aiGenerator': 'AI生成器',
    'nav.gallery': '画廊',
    'nav.about': '关于我们',
    'nav.getStarted': '开始使用',
    'hero.title': '将你的想法转化为惊艳的艺术品',
    'hero.subtitle': '使用我们先进的AI图像生成技术，在几秒钟内创作出美丽、独特的艺术作品',
    'hero.cta': '立即开始创作',
    'hero.learnMore': '了解更多',
    
         // What Section
     'what.title': '什么是Nano Banana？',
     'what.subtitle': '一个AI驱动的平台，将你的文字描述转化为惊艳的视觉艺术作品',
     'what.feature1.title': 'AI驱动生成',
     'what.feature1.desc': '先进的人工智能在几秒钟内将你的文字描述转化为惊艳、独特的艺术作品',
     'what.feature2.title': '多种艺术风格',
     'what.feature2.desc': '选择写实、卡通、油画、水彩画等数十种艺术风格',
     'what.feature3.title': '高质量输出',
     'what.feature3.desc': '生成高达4K质量的高分辨率图像，完美适用于打印和专业用途',
     'what.feature4.title': '极速生成',
     'what.feature4.desc': '在30秒内获得你的定制艺术作品。无需等待，无延迟 - 即时创作',
    
         // Why Section
     'why.title': '为什么选择Nano Banana？',
     'why.subtitle': '体验数字艺术创作的未来',
     'why.reason1.title': '隐私与安全',
     'why.reason1.desc': '你的提示词和生成的图像完全私密。我们绝不会在未经许可的情况下存储或分享你的创意内容',
     'why.reason1.stats': '100% 私密',
     'why.reason2.title': '创作者信赖',
     'why.reason2.desc': '加入超过50万名艺术家、设计师和创作者，他们都依赖Nano Banana进行创意项目',
     'why.reason2.stats': '50万+ 用户',
     'why.reason3.title': '行业领先',
     'why.reason3.desc': '我们的AI模型采用最新技术训练，相比其他平台提供卓越质量',
     'why.reason3.stats': '4.9/5 评分',
     'why.reason4.title': '持续改进',
     'why.reason4.desc': '我们根据用户反馈和技术进步定期更新AI模型并添加新功能',
     'why.reason4.stats': '每周更新',
     'why.stats.uptime': '运行时间保证',
     'why.stats.support': '客户支持',
     'why.stats.images': '已生成图像',
     'why.stats.styles': '艺术风格',
    
         // How Section
     'how.title': '如何使用',
     'how.subtitle': '创作杰作的三个简单步骤',
     'how.step1.title': '输入你的提示词',
     'how.step1.desc': '用简单的词汇描述你的愿景。尽可能创意和详细',
     'how.step2.title': '选择你的风格',
     'how.step2.desc': '选择各种艺术风格，如写实、卡通、油画等',
     'how.step3.title': '下载你的艺术',
     'how.step3.desc': '获得令人惊艳的AI生成艺术作品，高分辨率，随时可用',
    
    // Stats Section
    'stats.images': '已创建图像',
    'stats.users': '活跃用户',
    'stats.uptime': '运行时间',
    'stats.support': '支持服务',
    
         // Testimonials
     'testimonials.title': '用户评价',
     'testimonials.subtitle': '加入数千名满意的创作者，他们已经使用Nano Banana将想法转化为惊艳的艺术作品。以下是他们对Nano Banana体验的评价',
     'testimonials.user1.name': '陈莎拉',
     'testimonials.user1.role': '数字艺术家',
     'testimonials.user1.text': 'Nano Banana彻底改变了我的创意工作流程。AI生成图像的质量绝对令人惊艳，可用的风格种类令人难以置信。我每天都在客户项目中使用它。',
     'testimonials.user2.name': '马库斯·罗德里格斯',
     'testimonials.user2.role': '营销总监',
     'testimonials.user2.text': '作为营销专业人士，我需要快速获得高质量视觉内容。Nano Banana正是如此。速度和质量无与伦比，为我们团队节省了无数时间和预算。',
     'testimonials.user3.name': '艾米丽·沃森',
     'testimonials.user3.role': '内容创作者',
     'testimonials.user3.text': '起初我对AI艺术持怀疑态度，但Nano Banana完全改变了我的想法。图像如此详细和创意 - 有时甚至比我想象的更好。就像拥有一个个人艺术家。',
     'testimonials.user4.name': '金大卫',
     'testimonials.user4.role': '游戏开发者',
     'testimonials.user4.text': '对于概念艺术和游戏资源，Nano Banana是一个游戏改变者。多样的风格和快速迭代的能力显著加速了我们的开发过程。强烈推荐！',
     'testimonials.user5.name': '丽莎·汤普森',
     'testimonials.user5.role': '小企业主',
     'testimonials.user5.text': '经营小企业，我需要价格实惠但专业的营销视觉内容。Nano Banana正是如此。质量可以与昂贵的库存照片相媲美，但具有完全的定制性。',
     'testimonials.user6.name': '亚历克斯·约翰逊',
     'testimonials.user6.role': '自由设计师',
     'testimonials.user6.text': 'Nano Banana的创意可能性是无限的。我可以探索需要手动创建数小时的想法和概念。它已成为我设计工具库中的重要工具。',
    
         // FAQ Section
     'faq.title': '常见问题',
     'faq.subtitle': '关于Nano Banana你需要知道的一切',
     'faq.contact': '还有问题？我们随时为你提供帮助！',
     'faq.contactButton': '联系支持',
     'faq.q1': 'Nano Banana是如何工作的？',
     'faq.a1': 'Nano Banana使用先进的AI模型来解读你的文字描述并生成相应的图像。只需输入你想要看到的内容，选择你喜欢的风格，我们的AI就会在几秒钟内创建独特的艺术作品。',
     'faq.q2': '我可以生成什么类型的图像？',
     'faq.a2': '你可以生成几乎任何类型的图像 - 从写实照片到抽象艺术、卡通、风景、肖像、奇幻场景等等。我们的AI支持150多种不同的艺术风格，可以处理复杂、详细的提示词。',
     'faq.q3': '我可以创建的图像数量有限制吗？',
     'faq.a3': '免费用户每天最多可以生成10张图像。高级订阅用户可以获得无限生成、优先处理和访问高级功能的权限，如更高分辨率和独家艺术风格。',
     'faq.q4': '生成的图像分辨率是多少？',
     'faq.a4': '免费用户获得1024x1024像素的图像。高级用户可以生成高达4K分辨率（4096x4096像素）的图像，完美适用于打印和专业用途。',
     'faq.q5': '我可以商业使用生成的图像吗？',
     'faq.a5': '是的！所有使用Nano Banana生成的图像都可以用于商业目的。你拥有创作的完全权利，包括销售、修改和分发它们的权利。',
     'faq.q6': '生成图像需要多长时间？',
     'faq.a6': '大多数图像在15-30秒内生成。高级用户享受优先处理，在高峰时段可以将生成时间缩短到仅10秒。',
     'faq.q7': 'Nano Banana与其他AI生成器有什么不同？',
     'faq.a7': 'Nano Banana专注于质量、速度和用户体验。我们使用最新的AI模型，提供比竞争对手更多的艺术风格，提供更好的提示词理解，并保持行业最高的图像质量标准。',
     'faq.q8': '我的数据安全私密吗？',
     'faq.a8': '绝对安全。我们认真对待隐私。你的提示词和生成的图像都经过加密，绝不会与第三方共享。你可以随时删除你的账户和所有相关数据。',
    
         // Footer
     'footer.company': '公司',
     'footer.product': '产品',
     'footer.support': '支持',
     'footer.legal': '法律',
     'footer.copyright': '© 2025 Nano Banana. 保留所有权利。',
     'footer.madeWith': '为创作者用心制作 ❤️',
     'footer.poweredBy': 'AI驱动',
     'footer.about': '关于我们',
     'footer.careers': '招聘',
     'footer.press': '新闻',
     'footer.blog': '博客',
     'footer.features': '功能',
     'footer.pricing': '价格',
     'footer.api': 'API',
     'footer.help': '帮助中心',
     'footer.community': '社区',
     'footer.contact': '联系我们',
     'footer.terms': '服务条款',
     'footer.privacy': '隐私政策',
     'footer.cookies': 'Cookie政策',
     'footer.gdpr': 'GDPR',
     'footer.description': '使用Nano Banana的尖端AI技术，将你的想象力转化为惊艳的艺术作品。通过简单的文字提示，创作、分享和发现令人惊叹的图像。',
    
         // Call to Action
     'cta.title': '准备好创作你的杰作了吗？',
     'cta.subtitle': '加入已经在使用Nano Banana的数千名艺术家和创作者',
     'cta.button': '立即开始',
     'cta.badge': '今天开始创作',
     'cta.pricing': '查看价格',
     'cta.stats.images': '已创建图像',
     'cta.stats.users': '活跃用户',
     'cta.stats.uptime': '运行时间',
     'cta.stats.support': '支持服务',
     'testimonials.stats.averageRating': '平均评分',
     'testimonials.stats.happyUsers': '满意用户',
     'testimonials.stats.imagesGenerated': '已生成图像',
     'testimonials.stats.satisfactionRate': '满意度',
    
         // Gallery
     'gallery.title': '创作画廊',
     'gallery.subtitle': '探索我们社区使用Nano Banana AI技术创作的惊艳艺术作品。获得灵感并创作你自己的杰作',
     'gallery.loadMore': '加载更多作品',
     'gallery.prompt': '提示词：',
     'gallery.image1.title': '神秘森林',
     'gallery.image1.desc': '一个充满发光蘑菇和空灵光芒的魔法森林',
     'gallery.image2.title': '未来城市景观',
     'gallery.image2.desc': '一个拥有霓虹灯和飞行汽车的赛博朋克城市',
     'gallery.image3.title': '海上日落',
     'gallery.image3.desc': '一个充满活力日落色彩的宁静海洋场景',
     'gallery.image4.title': '山景',
     'gallery.image4.desc': '拥有戏剧性云彩和光线的雄伟山脉',
     'gallery.image5.title': '太空银河',
     'gallery.image5.desc': '远处星系和星云的惊艳景观',
     'gallery.image6.title': '抽象艺术',
     'gallery.image6.desc': '充满流动色彩的 vibrant 抽象构图',
     'gallery.image7.title': '野生动物肖像',
     'gallery.image7.desc': '一个雄伟野生动物的详细肖像',
     'gallery.image8.title': '建筑奇迹',
     'gallery.image8.desc': '拥有独特几何图案的现代建筑',
     'gallery.image9.title': '复古汽车',
     'gallery.image9.desc': '怀旧环境中的经典复古汽车',
     'gallery.prompt1': '魔法森林，发光蘑菇，空灵光线，奇幻艺术',
     'gallery.prompt2': '赛博朋克城市，霓虹灯，飞行汽车，未来建筑',
     'gallery.prompt3': '海上日落，活力色彩，平静波浪，黄金时刻',
     'gallery.prompt4': '雄伟山脉，戏剧性云彩，史诗风景摄影',
     'gallery.prompt5': '远处星系，彩色星云，太空摄影，星星',
     'gallery.prompt6': '抽象艺术，活力色彩，流动图案，数字绘画',
     'gallery.prompt7': '野生动物肖像，详细毛发，自然栖息地，专业摄影',
     'gallery.prompt8': '现代建筑，几何图案，玻璃和钢铁，城市设计',
     'gallery.prompt9': '复古汽车，经典设计，怀旧氛围，复古摄影',
     'draw.prompt': '生成自提示词：',
     'hero.examplePrompt': '几只鸭子在水中游泳的场景',
     'draw.title': 'AI图像生成器',
     'draw.subtitle': '使用我们先进的AI技术，将你的想法转化为惊艳的艺术作品',
     'draw.promptPlaceholder': '描述你想要看到的内容...',
     'draw.styleLabel': '艺术风格',
     'draw.sizeLabel': '图像尺寸',
     'draw.generateButton': '生成图像',
     'draw.generating': '生成中...',
     'draw.downloadButton': '下载',
     'draw.favoriteButton': '收藏',
     'draw.regenerateButton': '重新生成',
     'draw.successMessage': '图像生成成功！',
     'draw.errorMessage': '生成失败，请重试',
     'draw.waitingForGeneration': '等待生成',
     'draw.success': '成功',
     'draw.describeYourIdea': '描述你的创意',
     'draw.describeYourIdeaDesc': '详细描述你想要生成的图片内容',
     'draw.result': '生成结果',
     'draw.enterPromptAndClick': '输入提示词并点击生成按钮',
     'draw.styleRealistic': '🎭 写实风格 - 逼真的照片效果',
     'draw.styleAnime': '🎌 动漫风格 - 日式动漫风格',
     'draw.styleOilPainting': '🖼️ 油画风格 - 古典油画艺术',
     'draw.styleWatercolor': '💧 水彩风格 - 柔和的水彩画',
     'draw.styleSketch': '✏️ 素描风格 - 黑白素描艺术',
     'draw.sizeSquare': '⬜ 正方形',
     'draw.sizePortrait': '📱 竖版',
     'draw.sizeLandscape': '🖥️ 横版',
     'draw.sizeWidescreen': '🎬 宽屏',
     'draw.sizeMobilePortrait': '📱 手机竖版',
     'draw.tip': '提示：描述越详细，生成的图片越符合你的想象',
     'draw.generatedImage': '生成的图片',
     'draw.generationFailed': '生成失败',
     'about.badge': '关于Nano Banana',
     'about.title': '革新AI艺术创作',
     'about.subtitle': 'Nano Banana处于AI驱动创意的前沿，赋能艺术家、设计师和创作者，通过尖端人工智能技术将最狂野的想象力变为现实。',
     'about.mission.title': '我们的使命',
     'about.mission.desc': '通过让专业级AI图像生成技术为每个人所用，实现艺术创作的民主化。我们相信创意应该没有界限，技术应该放大人类想象力，而不是取代它。',
     'about.vision.title': '我们的愿景',
     'about.vision.desc': '一个任何人都能在几秒钟内创作惊艳艺术作品的世界，想法从脑海自由流向画布，AI成为人类表达和创新的终极创意伙伴。',
     'about.feature1.title': '先进AI技术',
     'about.feature1.desc': '由最先进的机器学习模型驱动，提供高质量、创意和独特的艺术作品生成。',
     'about.feature2.title': '以用户为中心的设计',
     'about.feature2.desc': '为所有技能水平的创作者设计的直观界面，从初学者到专业艺术家和设计师。',
     'about.feature3.title': '隐私与安全',
     'about.feature3.desc': '企业级安全措施，保护您的创意作品，确保您的知识产权安全。',
     'about.stats.images': '已创建图像',
     'about.stats.users': '活跃用户',
     'about.stats.uptime': '运行时间',
     'about.stats.support': '支持服务',
     'about.values.title': '我们的价值观',
     'about.values.subtitle': '这些核心原则指导我们在Nano Banana所做的一切',
     'about.value1.title': '卓越',
     'about.value1.desc': '我们在服务的每个方面都追求卓越，从AI质量到用户体验。',
     'about.value2.title': '创意',
     'about.value2.desc': '我们庆祝和培养创意，相信它是人类进步的基础。',
     'about.value3.title': '社区',
     'about.value3.desc': '我们建立并支持一个充满活力的创作者、艺术家和创新者社区。',
     
     // Privacy Policy
     'privacy.badge': '隐私与安全',
     'privacy.title': '隐私政策',
     'privacy.lastUpdated': '最后更新：2025年1月',
     'privacy.section1.title': '我们收集的信息',
     'privacy.section1.desc': '我们收集你直接提供给我们的信息，例如当你创建账户、使用我们的AI图像生成服务或联系我们的支持时。',
     'privacy.section1.item1': '账户信息（邮箱、用户名）',
     'privacy.section1.item2': '使用数据和生成的图像',
     'privacy.section1.item3': '通信偏好',
     'privacy.section1.item4': '关于你设备和使用情况的技术信息',
     'privacy.section2.title': '我们如何使用你的信息',
     'privacy.section2.desc': '我们使用收集的信息来提供、维护和改进我们的服务：',
     'privacy.section2.item1': '根据你的提示词处理和生成AI图像',
     'privacy.section2.item2': '提供客户支持并回应询问',
     'privacy.section2.item3': '改进我们的AI模型和服务质量',
     'privacy.section2.item4': '发送重要更新和服务通知',
     'privacy.section2.item5': '确保安全并防止欺诈',
     'privacy.section3.title': '数据安全',
     'privacy.section3.desc': '我们实施适当的安全措施来保护你的个人信息：',
     'privacy.section3.item1': '传输和存储数据的加密',
     'privacy.section3.item2': '定期安全审计和更新',
     'privacy.section3.item3': '访问控制和身份验证措施',
     'privacy.section3.item4': '安全的数据中心和基础设施',
     'privacy.section4.title': '数据共享',
     'privacy.section4.desc': '我们不会向第三方出售、交易或出租你的个人信息。我们可能仅在以下情况下共享信息：',
     'privacy.section4.item1': '获得你的明确同意',
     'privacy.section4.item2': '遵守法律义务',
     'privacy.section4.item3': '保护我们的权利和安全',
     'privacy.section4.item4': '与协助我们运营的可信服务提供商',
     'privacy.section5.title': '你的权利',
     'privacy.section5.desc': '你有权：',
     'privacy.section5.item1': '访问和审查你的个人信息',
     'privacy.section5.item2': '更新或纠正不准确的信息',
     'privacy.section5.item3': '请求删除你的数据',
     'privacy.section5.item4': '选择退出营销通信',
     'privacy.section5.item5': '以便携格式导出你的数据',
     'privacy.section6.title': '联系我们',
     'privacy.section6.desc': '如果你对本隐私政策或我们的数据实践有任何问题，请联系我们：',
     'privacy.section6.email': '邮箱：privacy@nanobananamodle.com',
     'privacy.section6.response': '我们将在24小时内回复你的询问。',
     
     // Terms of Service
     'terms.badge': '法律与条款',
     'terms.title': '服务条款',
     'terms.lastUpdated': '最后更新：2025年1月',
     'terms.section1.title': '条款接受',
     'terms.section1.desc': '通过访问和使用Nano Banana的AI图像生成服务，你同意受这些服务条款的约束。如果你不同意这些条款，请不要使用我们的服务。',
     'terms.section2.title': '服务描述',
     'terms.section2.desc': 'Nano Banana提供AI驱动的图像生成服务，允许用户从文字描述创建艺术作品。我们的服务包括：',
     'terms.section2.item1': '使用先进AI模型的文本到图像生成',
     'terms.section2.item2': '多种艺术风格和定制选项',
     'terms.section2.item3': '各种格式的高质量图像输出',
     'terms.section2.item4': '用户友好的界面和工具',
     'terms.section2.item5': '客户支持和协助',
     'terms.section3.title': '用户责任',
     'terms.section3.desc': '作为我们服务的用户，你同意：',
     'terms.section3.item1': '提供准确和适当的文本提示词',
     'terms.section3.item2': '尊重知识产权和版权法',
     'terms.section3.item3': '不将服务用于非法或有害目的',
     'terms.section3.item4': '不尝试逆向工程或黑客攻击我们的系统',
     'terms.section3.item5': '维护你账户凭据的安全性',
     'terms.section3.item6': '遵守所有适用的法律和法规',
     'terms.section4.title': '内容指南',
     'terms.section4.desc': '你不得使用我们的服务生成以下内容：',
     'terms.section4.item1': '包含仇恨言论、暴力或歧视',
     'terms.section4.item2': '侵犯知识产权',
     'terms.section4.item3': '色情或不当内容',
     'terms.section4.item4': '促进非法活动或有害行为',
     'terms.section4.item5': '未经同意包含他人的个人信息',
     'terms.section4.item6': '旨在欺骗或误导',
     'terms.section5.title': '知识产权',
     'terms.section5.desc': '关于你使用我们服务生成的图像：',
     'terms.section5.item1': '你保留生成图像的所有权',
     'terms.section5.item2': '你可以将图像用于个人和商业目的',
     'terms.section5.item3': '我们保留使用生成图像改进服务的权利',
     'terms.section5.item4': '你有责任确保你有权使用任何引用的内容',
     'terms.section6.title': '服务可用性',
     'terms.section6.desc': '我们努力保持高服务可用性，但不能保证：',
     'terms.section6.item1': '100%的运行时间或持续可用性',
     'terms.section6.item2': '高峰使用期间的即时响应时间',
     'terms.section6.item3': '与所有设备或浏览器的兼容性',
     'terms.section6.item4': '无限制的使用',
     'terms.section7.title': '责任限制',
     'terms.section7.desc': 'Nano Banana对因使用我们的服务而产生的任何间接、偶然、特殊、后果性或惩罚性损害不承担责任。',
     'terms.section8.title': '条款变更',
     'terms.section8.desc': '我们保留随时修改这些条款的权利。我们将通过电子邮件或通过我们的服务通知用户重大变更。变更后继续使用构成对新条款的接受。',
     'terms.section9.title': '联系信息',
     'terms.section9.desc': '如果你对这些服务条款有任何问题，请联系我们：',
     'terms.section9.email': '邮箱：legal@nanobananamodle.com',
     'terms.section9.response': '我们将在24小时内回复你的询问。',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'zh'>('en'); // 默认英文，避免水合错误
  
  // 在客户端挂载后从localStorage读取语言设置
  useEffect(() => {
    const savedLanguage = localStorage.getItem('nano-banana-language');
    if (savedLanguage === 'zh' || savedLanguage === 'en') {
      setLanguage(savedLanguage);
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const handleSetLanguage = (lang: 'en' | 'zh') => {
    setLanguage(lang);
    // 保存到localStorage
    if (typeof window !== 'undefined') {
      localStorage.setItem('nano-banana-language', lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
